# Generated by Django 3.1.4 on 2021-01-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectspage_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 0, 55, 41, 737229)),
        ),
    ]
