# Generated by Django 3.1.4 on 2021-01-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210110_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='date_started',
            field=models.DateField(),
        ),
    ]
