# Generated by Django 3.1.4 on 2021-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210110_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='languages_used',
            field=models.TextField(help_text='List all the languages used seperating by comma and connecting the last language with an "and"', max_length=100),
        ),
    ]
