# Generated by Django 3.1.4 on 2021-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210110_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='summary',
            field=models.TextField(help_text='Give a brief summary of the project. Additional details may be included in this page further down if necessary.', max_length=500),
        ),
    ]
