# Generated by Django 3.1.4 on 2021-01-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210110_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectslistingpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Smaller heading under the main title page. Max 100 words.', max_length=100),
        ),
    ]
